#!/usr/bin/env bash
# Stops everything (via stop.sh) and cleans build/autogenerated artifacts.
# Run with: ./clean.sh              (stop + clean build output, keep DB data & node_modules)
#           ./clean.sh --volumes    (also wipe docker volumes, i.e. Postgres data)
#           ./clean.sh --deep       (also remove node_modules everywhere - you'll need to reinstall)
#           ./clean.sh --stop-only  (equivalent to running ./stop.sh, no cleanup)
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

WIPE_VOLUMES=false
STOP_ONLY=false
DEEP_CLEAN=false
SERVICES=(auth-service event-service booking-service)

for arg in "$@"; do
  case "$arg" in
    --volumes) WIPE_VOLUMES=true ;;
    --stop-only) STOP_ONLY=true ;;
    --deep) DEEP_CLEAN=true ;;
  esac
done

./stop.sh --processes

echo "==> Stopping infra containers"
if $WIPE_VOLUMES; then
  docker compose -f infra/docker-compose.yml down -v
  echo "    postgres/redis/redpanda data volumes wiped"
else
  docker compose -f infra/docker-compose.yml down
fi

if $STOP_ONLY; then
  echo "Done (stop-only)."
  exit 0
fi

echo "==> Cleaning Maven build output for each service"
for svc in "${SERVICES[@]}"; do
  if [ -d "services/$svc" ]; then
    echo "    cleaning $svc"
    (cd "services/$svc" && ./mvnw -q clean)
  fi
done

echo "==> Cleaning notification-service build output"
rm -rf services/notification-service/dist

echo "==> Cleaning root aggregator build output"
[ -d target ] && rm -rf target

echo "==> Cleaning client build/autogenerated output"
if [ -d client ]; then
  rm -rf client/.next
  rm -rf client/out
  rm -rf client/coverage
  rm -f client/tsconfig.tsbuildinfo
fi

echo "==> Removing run artifacts"
rm -rf logs
rm -rf .pids

if $DEEP_CLEAN; then
  echo "==> Deep clean: removing node_modules (client + notification-service + root)"
  rm -rf node_modules
  rm -rf client/node_modules
  rm -rf services/notification-service/node_modules
  echo "    run 'pnpm install' before starting again"
fi

echo "Done. (--volumes wipes DB data, --deep also removes node_modules, --stop-only skips cleanup.)"
