events {}
http {
  upstream auth_service { server auth-service:8081; }
  upstream event_service { server event-service:8082; }
  upstream booking_service { server booking-service:8083; }
  upstream notification_service { server notification-service:3003; }
  server {
    listen 8080;
    location /auth/ { proxy_pass http://auth_service/; }
    location /events/ { proxy_pass http://event_service/; }
    location /bookings/ { proxy_pass http://booking_service/; }
    location /wallet/ { proxy_pass http://booking_service/; }
    location /notifications/ { proxy_pass http://notification_service/; }
    location /health { return 200 "ok\n"; }
  }
}

