spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:15432/grabmyticket}
    username: ${DATABASE_USERNAME:grabmyticket}
    password: ${DATABASE_PASSWORD:grabmyticket}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
