<#
.SYNOPSIS
  One-time loader: downloads GeoNames' cities15000 dataset (every city with
  population >= 15,000, ~25k rows) plus countryInfo.txt, and generates a
  Flyway migration SQL file with INSERT statements for event-service's
  `cities` table - the real, full-scale successor to V6__seed_cities.sql's
  ~120-city hand-curated starter set (see that file's header comment, which
  pointed at this script).

.DESCRIPTION
  Run this once, review the generated SQL file, rename it to the correct
  next Vn in services/event-service/src/main/resources/db/migration/, then
  commit it as a normal Flyway migration.

  Not run in CI or on app startup - this is a manual, one-time data-loading
  step, same category as scripts/check-services.ps1's local dev tooling.

.NOTES
  admin_name (state/province) is left NULL for every generated row.
  GeoNames' admin1 codes need a second lookup file (admin1CodesASCII.txt)
  to resolve to a human-readable name ("US.CA" -> "California"), which
  this script deliberately skips to stay single-purpose - admin_name is
  nullable in the schema, so this is a cosmetic gap only, not a blocker.
  V6's curated ~120 rows already have decent admin_name coverage; this
  script adds a NEW migration on top of those, it doesn't touch or
  replace V6.
#>

$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$workDir = Join-Path $PSScriptRoot ".geonames-tmp"
New-Item -ItemType Directory -Force -Path $workDir | Out-Null

$citiesZipUrl = "https://download.geonames.org/export/dump/cities15000.zip"
$countryInfoUrl = "https://download.geonames.org/export/dump/countryInfo.txt"
$citiesZipPath = Join-Path $workDir "cities15000.zip"
$countryInfoPath = Join-Path $workDir "countryInfo.txt"

Write-Host "Downloading cities15000.zip (~25k cities, population >= 15,000)..."
Invoke-WebRequest -Uri $citiesZipUrl -OutFile $citiesZipPath

Write-Host "Downloading countryInfo.txt (ISO code -> country name)..."
Invoke-WebRequest -Uri $countryInfoUrl -OutFile $countryInfoPath

Write-Host "Extracting..."
Expand-Archive -Path $citiesZipPath -DestinationPath $workDir -Force

# ISO alpha-2 -> country name, from countryInfo.txt (tab-separated; lines
# starting with # are comments/header; column 0 = ISO code, column 4 = name).
$countryNames = @{}
Get-Content $countryInfoPath | ForEach-Object {
    if ($_ -notmatch "^#" -and $_.Trim().Length -gt 0) {
        $cols = $_ -split "`t"
        if ($cols.Length -ge 5) { $countryNames[$cols[0]] = $cols[4] }
    }
}

function Sql-Escape([string]$value) {
    if ([string]::IsNullOrEmpty($value)) { return "NULL" }
    return "'" + ($value -replace "'", "''") + "'"
}

# cities15000.txt columns (tab-separated, no header): 1=name, 4=latitude,
# 5=longitude, 8=country code, 14=population, 17=timezone.
$citiesTxtPath = Join-Path $workDir "cities15000.txt"
$rows = @()
Get-Content $citiesTxtPath | ForEach-Object {
    $cols = $_ -split "`t"
    if ($cols.Length -lt 19) { return }

    $countryCode = $cols[8]
    if (-not $countryNames.ContainsKey($countryCode)) { return }

    $name = Sql-Escape $cols[1]
    $lat = $cols[4]
    $lng = $cols[5]
    $population = $cols[14]
    $timezone = Sql-Escape $cols[17]
    $countryName = Sql-Escape $countryNames[$countryCode]
    $countryCodeSql = Sql-Escape $countryCode

    $rows += "($name, $countryCodeSql, $countryName, NULL, $lat, $lng, $timezone, $population)"
}

Write-Host "Formatted $($rows.Count) rows."

$header = @"
-- Auto-generated by scripts/seed-cities-from-geonames.ps1 from GeoNames'
-- cities15000 dataset (population >= 15,000) + countryInfo.txt. Adds to,
-- does not replace, V6__seed_cities.sql's curated starter set.
--
-- admin_name is NULL for every row here - see the generator script's
-- header comment for why (nullable in the schema, cosmetic gap only).
--
-- RENAME THIS FILE before committing: set its Vn to whatever version is
-- actually next in this migration folder - this script does not check.
"@

$batchSize = 500
$batches = for ($i = 0; $i -lt $rows.Count; $i += $batchSize) {
    $end = [Math]::Min($i + $batchSize - 1, $rows.Count - 1)
    "INSERT INTO cities (name, country_code, country_name, admin_name, latitude, longitude, timezone, population) VALUES`n" + `
        ($rows[$i..$end] -join ",`n") + ";"
}

$outputPath = Join-Path $PSScriptRoot "..\services\event-service\src\main\resources\db\migration\V99__seed_cities_geonames.sql"
($header, "", ($batches -join "`n`n")) -join "`n" | Set-Content -Path $outputPath -Encoding UTF8

Write-Host "Done: $outputPath"
Write-Host "Next steps: 1) review the file  2) rename V99 to the correct next version  3) delete $workDir  4) commit as a normal migration."
