import { EventCategory } from "@/enums/event-category.enum";
import { EventStatus } from "@/enums/event-status.enum";
import type { DashboardEvent } from "@/interfaces/event.interface";

export const MOCK_EVENTS: DashboardEvent[] = [
  { id: "food-exhibition", title: "Food Exhibition", category: EventCategory.FoodCulinary, status: EventStatus.Active, price: 10, date: "November 2, 2025", time: "3:00 PM", location: { venue: "Digana Main Hall", city: "Kandy", lat: 7.2906, lng: 80.6337 }, ticketsSoldPct: 55, description: "Food Exhibition 2025 will be held on November 2, 2025, at 3:00 PM in the Digana Main Hall, Kandy. Join us for an exciting showcase of culinary creativity featuring delicious dishes, live cooking demos, and local food stalls.", totalTicketsBooked: 5340, attendeeRatePct: 75 },
  { id: "ai-make-us-better", title: "AI Make us Better", category: EventCategory.Technology, status: EventStatus.Active, price: 20, date: "November 6, 2025", time: "9:00 AM", location: { venue: "Jublee Hall", city: "Colombo 03", lat: 6.9271, lng: 79.8612 }, ticketsSoldPct: 68, description: "A day of talks and workshops on applying AI responsibly across product, design and engineering teams.", totalTicketsBooked: 4120, attendeeRatePct: 81 },
  { id: "fashion-empire", title: "Fashion Empire", category: EventCategory.Fashion, status: EventStatus.Active, price: 5, date: "November 27, 2025", time: "10:00 AM", location: { venue: "Hill's Hall", city: "Dehiwala", lat: 6.8508, lng: 79.8654 }, ticketsSoldPct: 96, description: "A runway showcase spotlighting emerging local designers and their latest seasonal collections.", totalTicketsBooked: 2870, attendeeRatePct: 88 },
  { id: "how-to-camp", title: "How to Camp", category: EventCategory.OutdoorAdventure, status: EventStatus.Active, price: 60, date: "December 10, 2025", time: "4:30 PM", location: { venue: "Narangala Mountain", city: "Badulla", lat: 6.9934, lng: 81.055 }, ticketsSoldPct: 99, description: "A hands-on outdoor workshop covering campsite setup, fire safety and backcountry navigation.", totalTicketsBooked: 1980, attendeeRatePct: 92 },
  { id: "hip-hop-thugs", title: "Hip Hop Thugs", category: EventCategory.Music, status: EventStatus.Active, price: 90, date: "December 31, 2025", time: "6:00 PM", location: { venue: "Galle Face", city: "Colombo 1", lat: 6.9219, lng: 79.8437 }, ticketsSoldPct: 87, description: "A New Year's Eve headline show closing out the year with a full live band and guest MCs.", totalTicketsBooked: 6110, attendeeRatePct: 79 },
  { id: "balanced-diet", title: "Balanced Diet", category: EventCategory.HealthFitness, status: EventStatus.Active, price: 6, date: "January 6, 2026", time: "8:00 AM", location: { venue: "Main Hall", city: "Nuwara Eliya", lat: 6.9497, lng: 80.7891 }, ticketsSoldPct: 34, description: "A nutrition-focused morning session with registered dietitians on building sustainable eating habits.", totalTicketsBooked: 940, attendeeRatePct: 63 },
  { id: "code-with-us", title: "Code with Us", category: EventCategory.Technology, status: EventStatus.Active, price: "free", date: "January 30, 2026", time: "9:00 AM", location: { venue: "BMICH Main Hall", city: "Colombo 6", lat: 6.8951, lng: 79.8697 }, ticketsSoldPct: 72, description: "A free community coding day pairing students with mentors from local engineering teams.", totalTicketsBooked: 3300, attendeeRatePct: 84 },
  { id: "adventure-hiking", title: "Adventure Hiking", category: EventCategory.OutdoorAdventure, status: EventStatus.Active, price: 100, date: "February 14, 2026", time: "6:00 AM", location: { venue: "Pidruthalagala Mountain", city: "Kandy", lat: 7.0128, lng: 80.7649 }, ticketsSoldPct: 94, description: "A guided sunrise hike to Sri Lanka's highest peak, with breakfast at the summit.", totalTicketsBooked: 2210, attendeeRatePct: 90 },
];

export const UPCOMING_EVENT_IDS = ["food-exhibition", "ai-make-us-better"];

export const EVENT_STATUS_COUNTS = { active: 10, past: 19, draft: 7 };
